package(default_visibility = ["//visibility:public"])

load("//:setup.bzl", "kudu_cc_library", "kudu_cc_test", "kudu_proto_library")

kudu_proto_library(
    "metadata",
    proto_deps = ["//kudu/common:common_proto"],
)
